name: Keyin Production CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 'Production | Ortho'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.HOST }}
          SSH_USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Build and Deploy Keyin Ortho
        run: |
          ssh deploy '
          eval "$(ssh-agent -s)" &&
          ssh-add ~/.ssh/keyin-ortho &&
          export NVM_DIR=~/.nvm &&
          source ~/.nvm/nvm.sh &&
          cd /var/www/keyin-ortho &&
          git fetch origin ${{ github.head_ref }} &&
          git checkout ${{ github.head_ref }} &&
          git pull origin ${{ github.head_ref }} &&
          npm ci -f --silent &&
          npm run build &&
          sudo service nginx restart
          '
